spring:
  application:
    name: ms-bank-accounts
  data:
    mongodb:
      uri: mongodb://localhost:27017/ms-bank-account
server:
  port: 8080
api:
  client:
    url: http://localhost:8085
  credit:
    url: http://localhost:8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Dirección del servidor Eureka
    register-with-eureka: true # Permite registrarse en Eureka
    fetch-registry: true # Obtiene el registro de servicios de Eureka
  instance:
    prefer-ip-address: true # Utiliza la IP en lugar del hostname