spring:
  application:
    name: ms-client
  data:
    mongodb:
      uri: mongodb://localhost:27017/ms-customer
server:
  port: 8085
api:
  bank:
    url: http://localhost:8080
  credit:
    url: http://localhost:8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Dirección del servidor Eureka
    register-with-eureka: true # Permite registrarse en Eureka
    fetch-registry: true # Obtiene el registro de servicios de Eureka
  instance:
    prefer-ip-address: true # Utiliza la IP en lugar del hostname