spring:
  application:
    name: ms-credit
  data:
    mongodb:
      uri: mongodb://localhost:27017/ms-credit
server:
  port: 8082
api:
  client:
    url: http://localhost:8085
  bank:
    url: http://localhost:8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Dirección del servidor Eureka
    register-with-eureka: true # Permite registrarse en Eureka
    fetch-registry: true # Obtiene el registro de servicios de Eureka
  instance:
    prefer-ip-address: true # Utiliza la IP en lugar del hostname


resilience4j.circuitbreaker:
  instances:
    myService:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      failureRateThreshold: 50
      waitDurationInOpenState: 2000
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: COUNT_BASED

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info   # Habilita múltiples endpoints
  endpoint:
    refresh:
      enabled: true
