spring:
  application:
    name: ms-client
  data:
    mongodb:
      uri: mongodb://localhost:27017/bank
server:
  port: 8085
api:
  bank:
    url: http://localhost:8080
  credit:
    url: http://localhost:8082