openapi: 3.0.0
info:
  title: Banco API
  description: API para obtener informaci贸n de cuentas bancarias
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /accounts/bank:
    get:
      summary: Obtener informaci贸n de cuentas bancarias
      operationId: getBankAccounts
      tags:
        - accounts
      responses:
        '200':
          description: Lista de cuentas bancarias
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/BankAccountResponse"
  /accounts/bank/{id}:
    get:
      summary: Obtener informaci贸n de una cuenta bancaria por ID
      operationId: getBankAccountById
      tags:
        - accounts
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: 67af7919c77cae749a03414d
      responses:
        '200':
          description: Informaci贸n de la cuenta bancaria
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BankAccountResponse"
components:
  schemas:
    BankAccountResponse:
      type: object
      properties:
        id:
          type: string
          example: 67af7919c77cae749a03414d
        type:
          type: string
          example: SAVINGS
        clientId:
          type: string
          example: 67a42a1dc1ef9d814f3258a8
        balance:
          type: number
          format: double
          example: 400.0
        currency:
          type: string
          example: PEN
        openingDate:
          type: string
          format: date-time
          example: 2025-02-14T12:10:49.687
        maintenance:
          type: number
          format: double
          example: 0.0
        limitMovements:
          type: integer
          example: 0
        dayWithdrawalDeposit:
          type: string
          nullable: true
          example: null
        movements:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
                example: withdraw
              amount:
                type: number
                format: double
                example: 100.0
              date:
                type: string
                format: date-time
                example: 2025-02-14T12:11:21.236
        holders:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                example: harold
              document:
                type: string
                example: 76123154
              documentType:
                type: string
                example: DNI
        authorizedSignatories:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                example: harold
              document:
                type: string
                example: 76123154
              documentType:
                type: string
                example: DNI