openapi: 3.0.0
info:
  title: Banco API
  description: API para obtener información de cuentas bancarias
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /accounts/bank:
    get:
      summary: Obtener información de cuentas bancarias
      operationId: getBankAccounts
      tags:
        - accounts
      responses:
        '200':
          description: Lista de cuentas bancarias
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/BankAccountResponse"
  /accounts/bank/{id}:
    get:
      summary: Obtener información de una cuenta bancaria por ID
      operationId: getBankAccountById
      tags:
        - accounts
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: 67af7919c77cae749a03414d
      responses:
        '200':
          description: Información de la cuenta bancaria
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BankAccountResponse"
  /accounts/register:
    post:
      summary: Registrar una nueva cuenta bancaria
      operationId: registerBankAccount
      tags:
        - accounts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  example: CURRENT
                clientId:
                  type: string
                  example: 67a42e3460443d2d12224b7b
                currency:
                  type: string
                  example: PEN
                amount:
                  type: number
                  format: double
                  example: 200.0
                holders:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        example: Anita Tintaya
                      document:
                        type: string
                        example: 74124577
                      documentType:
                        type: string
                        example: DNI
                authorizedSignatories:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        example: Anita Tintaya
                      document:
                        type: string
                        example: 74124577
                      documentType:
                        type: string
                        example: DNI
      responses:
        '200':
          description: Cuenta bancaria registrada exitosamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BankAccountResponse"
  /accounts/deposit:
    post:
      summary: Realizar un depósito en una cuenta bancaria
      operationId: depositToBankAccount
      tags:
        - accounts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TransactionRequest"
      responses:
        '200':
          description: Depósito realizado exitosamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BankAccountResponse"
  /accounts/withdraw:
    post:
      summary: Realizar un retiro de una cuenta bancaria
      operationId: withdrawFromBankAccount
      tags:
        - accounts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionRequest'
      responses:
        '200':
          description: Retiro realizado exitosamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BankAccountResponse"
  /accounts/transfer:
    post:
      summary: Realizar una transferencia entre cuentas bancarias
      operationId: transferBetweenAccounts
      tags:
        - accounts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferRequest'
      responses:
        '200':
          description: Transferencia exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Transferencia exitosa
components:
  schemas:
    TransferRequest:
      type: object
      properties:
        sourceAccountId:
          type: string
          example: 67b5442f6a59ca515b645d6a
        destinationAccountId:
          type: string
          example: 67b5442f6a59ca515b645d6a
        amount:
          type: number
          format: double
          example: 2970.00
    TransactionRequest:
      type: object
      properties:
        cardId:
          type: string
          example: 67af7919c77cae749a03414d
        amount:
          type: number
          format: double
          example: 200.00
    BankAccountResponse:
      type: object
      properties:
        id:
          type: string
          example: 67af7919c77cae749a03414d
        type:
          type: string
          example: SAVINGS
        clientId:
          type: string
          example: 67a42a1dc1ef9d814f3258a8
        balance:
          type: number
          format: double
          example: 400.0
        currency:
          type: string
          example: PEN
        openingDate:
          type: string
          format: date-time
          example: 2025-02-14T12:10:49.687
        maintenance:
          type: number
          format: double
          example: 0.0
        limitMovements:
          type: integer
          example: 0
        dayWithdrawalDeposit:
          type: string
          example: null
        movements:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
                example: withdraw
              amount:
                type: number
                format: double
                example: 100.0
              date:
                type: string
                format: date-time
                example: 2025-02-14T12:11:21.236
        holders:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                example: harold
              document:
                type: string
                example: 76123154
              documentType:
                type: string
                example: DNI
        authorizedSignatories:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                example: harold
              document:
                type: string
                example: 76123154
              documentType:
                type: string
                example: DNI