server:
  port: 9070

spring:
  application:
    name: ms-user
  data:
    mongodb:
      uri: mongodb://localhost:27017/ms-user
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liv5zaQTDUnkPlAh
            client-secret: 06c2c818652e1fa248c72426acc737e91bd5f437
            scope: read:user
            redirect-uri: http://localhost:8080/login/oauth2/code/github
            authorization-grant-type: authorization_code
            client-name: GitHub
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user